---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: archlinux
    image: archlinux:latest
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: ubuntu1804
    image: ubuntu:18.04
  - name: ubuntu2004
    image: ubuntu:20.04
  - name: debian9
    image: debian:9
  - name: debian10
    image: debian:10
provisioner:
  name: ansible
verifier:
  name: testinfra
